//@author Lucas A. W. P. do Nascimento
package Trabalho2.huffman;

import javax.swing.ButtonGroup;
import static javax.swing.JOptionPane.showMessageDialog;

import Trabalho2.lista.ListaOrdenada;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lucas
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(rbCompactar);
        group.add(rbDescompactar);

        tfOrigem.setText("C:\\Huffman\\origem.txt");
        tfDestino.setText("C:\\Huffman\\destino.txt");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        buttonGroup2 = new ButtonGroup();
        buttonGroup3 = new ButtonGroup();
        buttonGroup4 = new ButtonGroup();
        buttonGroup5 = new ButtonGroup();
        buttonGroup6 = new ButtonGroup();
        rbCompactar = new javax.swing.JRadioButton();
        rbDescompactar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfOrigem = new javax.swing.JTextField();
        tfDestino = new javax.swing.JTextField();
        btProcessar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbCompactar.setText("Compactar");
        rbCompactar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCompactarActionPerformed(evt);
            }
        });

        rbDescompactar.setText("Descompactar");
        rbDescompactar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDescompactarActionPerformed(evt);
            }
        });

        jLabel1.setText("Arquivo origem");

        jLabel2.setText("Arquivo destino");

        tfOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOrigemActionPerformed(evt);
            }
        });

        tfDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDestinoActionPerformed(evt);
            }
        });

        btProcessar.setText("Processar");
        btProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcessarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbDescompactar)
                            .addComponent(rbCompactar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(tfOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btProcessar)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rbCompactar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbDescompactar)
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btProcessar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCompactarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCompactarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCompactarActionPerformed

    private void tfOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOrigemActionPerformed

    private void btProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcessarActionPerformed
        if (!rbCompactar.isSelected() && !rbDescompactar.isSelected()) {
            showMessageDialog(null, "Selecione uma opção");
        }
        //Compactar
        if (rbCompactar.isSelected()) {
            Huffman h = new Huffman();

            //Origem
            String diretorioArquivoOrigem = tfOrigem.getText();

            String conteudo = h.lerArquivo(diretorioArquivoOrigem);

            //cria lista de árvores binárias Huffman (Peso e Caracter)
            ListaOrdenada<ArvoreBinariaHuffman> lista = h.criarLista(conteudo);
            //monta árvore
            ArvoreBinariaHuffman arvoreFinal = h.montarArvore(lista);

            /*
            System.out.println(arvoreFinal.getRaiz().getInfo().getPeso());

            System.out.println(arvoreFinal.getRaiz().getEsquerda().getInfo().getPeso());
            System.out.println(arvoreFinal.getRaiz().getEsquerda().getEsquerda().getInfo().getCaractere());

            System.out.println(arvoreFinal.getRaiz().getDireita().getInfo().getPeso());
            System.out.println(arvoreFinal.getRaiz().getEsquerda().getDireita().getInfo().getCaractere());

            System.out.println(arvoreFinal.getRaiz().getDireita().getEsquerda().getInfo().getPeso());
            System.out.println(arvoreFinal.getRaiz().getDireita().getEsquerda().getEsquerda().getInfo().getCaractere());

            System.out.println(arvoreFinal.getRaiz().getDireita().getDireita().getInfo().getPeso());
            System.out.println(arvoreFinal.getRaiz().getDireita().getEsquerda().getDireita().getInfo().getCaractere());
             */
            //Destino
            String diretorioArquivoDestino = tfDestino.getText();
            int qtdDistintos = h.contarDistintos(conteudo);
            h.escreverArquivo(diretorioArquivoDestino, conteudo, qtdDistintos, arvoreFinal);
        }

        //Descompactar
        if (rbDescompactar.isSelected()) {
            Huffman h = new Huffman();

            //Origem
            String diretorioArquivoOrigem = tfOrigem.getText();
            String diretorioArquivoDestino = tfDestino.getText();
            
            String conteudo = h.lerArquivo(diretorioArquivoOrigem);
            
            h.descompactar(diretorioArquivoDestino, conteudo);

        }
    }//GEN-LAST:event_btProcessarActionPerformed

    private void rbDescompactarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDescompactarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDescompactarActionPerformed

    private void tfDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDestinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProcessar;
    private ButtonGroup buttonGroup1;
    private ButtonGroup buttonGroup2;
    private ButtonGroup buttonGroup3;
    private ButtonGroup buttonGroup4;
    private ButtonGroup buttonGroup5;
    private ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbCompactar;
    private javax.swing.JRadioButton rbDescompactar;
    private javax.swing.JTextField tfDestino;
    private javax.swing.JTextField tfOrigem;
    // End of variables declaration//GEN-END:variables
}
